version: '3'

services:
  neo4j:
    image: neo4j/neo4j-arm64-experimental:4.1.0-arm64
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./database/conf:/var/lib/neo4j/conf
      - ./database/data:/var/lib/neo4j/data
      - ./database/import:/var/lib/neo4j/import
      - ./database/logs:/logs
      - ./database/plugins:/var/lib/neo4j/plugins
  crawler:
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile
    image: wikicrawler:1.0.0
    volumes:
      - ./:/opt/
    ports:
      - "8888:8888"
    links: 
      - "neo4j:db"
    depends_on:
      - "neo4j"
    restart: always
    command: python app.py --action apicrawl